sudo: required

language: c

services:
  - docker

git:
  submodules: false

before_install:
  - git submodule update --init --recursive --depth=1

script:
  - docker run -v $PWD:/app -w /app jklmnn/gnat:gpl.2018.slim /bin/sh -c "apt-get update && apt-get install -y --no-install-recommends ca-certificates libxml2-utils && make test;"
